### ISSUE TITLE
Realizar pruebas de al menos una historia de usuario

### ISSUE THREAD

**Issue by SaraSama13** [DargyJML/ProyectoDesarrolloSoftware#38]

**Comment by FredyCalle** [comment]
Revisar si en las pruebas de historia de usuario, se requieren hacer pruebas de acuerdo a la madurez del proyecto actual.  Se podrían realizar pruebas con relación a los diseños de CSS y web, pero se requieren ubicar estas propuestas en sitios comunes para validarlos.  Con relación a los códigos actuales, estamos en etapas iniciales del crud.  Propongo reformular las historias de usuarios que nos permitan vincular la madurez de proyecto actual.
