### ISSUE TITLE
Testear la operaciones CRUD para verificar su correcto funcionamiento

### ISSUE THREAD

**Issue by SaraSama13** [DargyJML/ProyectoDesarrolloSoftware#41]

**Comment by FredyCalle** [comment]
Se realiza la compilación de los módulos sin problemas (Capas de: Persistencia, Dominio, Servicios y Consola) - 0 Warnings / 0 Errors
Verificación del CRUD de las siguientes clases:
- Municipios
- Deportistas

![Compilación del proyecto sin eventos](https://user-images.githubusercontent.com/90583287/134779951-970cd83a-8e4f-4a4d-b624-dc0164075dbf.JPG)

**Comment by FredyCalle** [comment]
**Ingresando municipio desde consola:**
![Ingresar municipio](https://user-images.githubusercontent.com/90583287/134780685-27373315-42b8-46cc-98c7-148ecb052667.JPG)

**Creación del municipio en la BD**
![Creación municipio BD](https://user-images.githubusercontent.com/90583287/134780733-4411fed5-7f8c-470f-b8e4-710d55046448.JPG)
