### ISSUE TITLE
Definir los lineamientos para testear la aplicación.

### ISSUE THREAD

**Issue by SaraSama13** [DargyJML/ProyectoDesarrolloSoftware#56]

**Comment by FredyCalle** [comment]
Como tengo el rol de Tester en el equipo, he estado realizado las consultas pertinentes a las pruebas unitarias al código C#.  He encontrado que existen tres módulos que nos permiten realizar las pruebas desde dotnet (MSTest, xUnit, NUnit), existe amplia documentación con xUnit, y por tanto decidí explorar este camino para desarrollar los entornos de prueba.

Fuente de consulta:
https://xunit.net/

Uso con .NET Core y línea de comandos.
https://xunit.net/docs/getting-started/netcore/cmdline

Quedo atento a las recomendaciones con relación al entorno escogido para las pruebas.
