### ISSUE TITLE
Documentar el proceso y resultados de los test.

### ISSUE THREAD

**Issue by SaraSama13** [DargyJML/ProyectoDesarrolloSoftware#58]

**Comment by FredyCalle** [comment]
**Realización de las pruebas unitarias C# en .Net Core utilizando dotnet test y xUnit**

Lo primero que realizamos es crear la estructura que nos almacenará las pruebas.
Comando utilizado en consola:
dotnet new sln -o Testing

el comando dotnet new sln (crea la carpeta Testing en el directorio del proyecto)
Antes:
![image](https://user-images.githubusercontent.com/90583287/135674496-49af40e8-a6ea-4369-8aa7-fbbd8faa70d9.png)

Después:
![image](https://user-images.githubusercontent.com/90583287/135674559-b8bef423-7fa6-4493-879d-6095daf1c2b6.png)

Luego nos ubicamos en la carpeta creada (Testing) y escribimos el siguiente comando para crear una biblioteca de clases (contendrá el código que se probará)
dotnet new classlib -o PrimeService

![image](https://user-images.githubusercontent.com/90583287/135674950-05e34881-970c-4bc5-8937-147a811de71f.png)

Renombramos el archivo Class1.cs a PrimeService.cs y codificamos la clase que lanzará un **NotImplementedException** con un mensaje que no está implementado.  

//Este segmento de código se encuentra también en prueba mientras se afina la referencia a las clases.

Continuamos con el siguiente comando para agregar la biblioteca de clases a la solución.

dotnet sln add ./PrimeService/PrimeService.csproj

Con el siguiente comando, creamos el proyecto Municipio.Tests en el directorio PrimeService utilizando xUnit como biblioteca de prueba.

dotnet new xunit -o Municipio.Tests
![image](https://user-images.githubusercontent.com/90583287/135675778-72208eb2-86b8-4451-b87e-5a040fc2872a.png)

Y agrega los paquetes de referencia al proyecto:
![image](https://user-images.githubusercontent.com/90583287/135676129-c2ac5d39-5a0f-4c76-b52b-845ca66edd31.png)

Luego agregamos PrimeService a la biblioteca de clases como una dependencia la proyecto Municipio.Tests con el siguiente comando:

dotnet add ./Municipio.Tests/Municipio.Tests.csproj reference ./PrimeService/PrimeService.csproj

![image](https://user-images.githubusercontent.com/90583287/135676887-f9334d43-4718-4143-bc61-577648c9f2c7.png)


Con estos comandos estamos preparando el entorno de pruebas unitarias con xUnit
