### ISSUE TITLE
Implementar formularios web para al menos la mitad de  las clases.

### ISSUE THREAD

**Issue by DargyJML** [DargyJML/ProyectoDesarrolloSoftware#59]

**Comment by jamesapm3871** [comment]
Crear Operaciones CRUD en C#  del modelo completo

Para la implementación del frontend se realiza la creación del complemento web.
 	

Dentro de esta carpeta en la sección de Pages, creamos una carpeta correspondiente a cada entidad a la que le implementaremos el CRUD.

 

Dentro de las nuevas carpetas de cada entidad hay 10 archivos, 5 con extensión cshtml y los otros con el agregado de .cs, cada pareja tiene por nombre uno relacionado a la función del crud que realizará, ya que para cada operación de éste se diseña un formulario.




Pero para que estas páginas funcionen es necesario agregar su acceso al index de la página principal desde el archivo _layout en la carpeta shared del frontend creado inicialmente.



Finalmente es necesario agregar los repositorios de la capa del dominio dentro del archivo Starup.cs alojado en la misma carpeta Frontend, pues de estos vienen los métodos del CRUD que se visualizarán en la pàgina web.



Realizamos la ejecución del código para confirmar la correcta ejecución del programa.
